services:
  operation-center:
    build:
      context: .
      dockerfile: Dockerfile
      target: operation-center
    ports:
      - "5000:5000/udp"
    container_name: operation-center
    environment:
      - RUST_LOG=info,zenoh=debug,RUST_BACKTRACE=1

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: test
    depends_on:
      - zenoh
      - databroker
    environment:
      - RUST_LOG=info,zenoh=debug,RUST_BACKTRACE=1
    networks:
      - kuksa

  zenoh:
    image: eclipse/zenoh:latest
    container_name: zenoh
    ports:
      - "7447:7447"
    networks:
      - kuksa

  databroker:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker:latest
    container_name: databroker
    command: [ "--insecure", "--vss", "/app/vss.json" ]
    volumes:
      - type: bind
        source: ./own_vss.json
        target: /app/vss.json
        read_only: true
    ports:
      - "30000:55555"
    networks:
      - kuksa

  databroker-cli:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker-cli:main
    container_name: databroker-cli
    depends_on:
      - databroker
    command:
      - "--server"
      - "databroker:55555"
    stdin_open: true
    tty: true
    networks:
      - kuksa

  provider:
    build:
      context: .
      dockerfile: Dockerfile
      target: provider
    container_name: provider
    depends_on:
      - zenoh
      - databroker
    environment:
      - RUST_LOG=info,zenoh=debug,RUST_BACKTRACE=1
    networks:
      - kuksa


networks:
  kuksa:
    driver: bridge