name: OperationCenter

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: operation-center
  IMAGE_TAG: latest

jobs:
  build-and-push:
    # Try to use the same version as in the Dockerfile
    runs-on: ubuntu-latest

    #    Pipeline executes if changes are made on the main branch, a pull request is made, or the branch name contains 'Pipeline'
    if: contains(github.ref,'Pipeline') || github.event_name == 'pull_request' || github.ref_name == 'main'

    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase repository env
        run: echo "REPOSITORY=${{ toLower(github.repository) }}" >> $GITHUB_ENV

      - name: Log in to ghcr
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (for emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}