name: OperationCenter

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
    packages: write # Allows action to publish packages
    
env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  REPOSITORY_NORMAL: ${{github.repository}}
  IMAGE_NAME: operation-center
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref,'pipeline') || github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Downcase REPOSITORY
      run: echo "REPOSITORY=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

    - name: Building image
      run: docker build -t $REGISTRY/$REPOSITORY/$IMAGE_NAME:$TAG .

    - name: Pushing image
      run: docker push $REGISTRY/$REPOSITORY/$IMAGE_NAME:$TAG
